// SPDX-FileCopyrightText: 2024-2026 Espressif Systems (Shanghai) CO LTD
//
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	mcpserver "mcp-server"
)

// catalogPath is the committed tool catalog, relative to this package.
const catalogPath = "../../../../docs/mcp/rainmaker-mcp.json"

// toolCatalog is what offline consumers read: the eval framework's MCP adapter and the docs
// generator both take this file as the answer to "what does the server expose", so its shape
// is a contract in its own right.
type toolCatalog struct {
	Name    string           `json:"name"`
	Version string           `json:"version"`
	Tools   []mcpserver.Tool `json:"tools"`
}

// Deliberately a plain test rather than a Ginkgo spec: it compares a committed file against
// generated bytes and must stay runnable on its own, since `make update-mcp-schema` uses the
// same code path to rewrite the file.
func TestToolCatalogMatchesSnapshot(t *testing.T) {
	generated, err := renderCatalog()
	if err != nil {
		t.Fatalf("failed to render the tool catalog: %v", err)
	}

	if os.Getenv("UPDATE_MCP_SCHEMA") == "1" {
		if err := os.MkdirAll(filepath.Dir(catalogPath), 0o755); err != nil {
			t.Fatalf("failed to create the catalog directory: %v", err)
		}
		if err := os.WriteFile(catalogPath, generated, 0o644); err != nil {
			t.Fatalf("failed to write the catalog: %v", err)
		}
		t.Logf("rewrote %s", catalogPath)
		return
	}

	committed, err := os.ReadFile(catalogPath)
	if err != nil {
		t.Fatalf("failed to read %s — run `make update-mcp-schema`: %v", catalogPath, err)
	}
	if string(committed) != string(generated) {
		t.Fatalf("the tool catalog is out of date with the registry.\n"+
			"A tool name, description or schema changed, which changes how models use this server.\n"+
			"Run `make update-mcp-schema` and review the diff before committing.\n\ncommitted:\n%s\n\ngenerated:\n%s",
			committed, generated)
	}
}

// renderCatalog builds the catalog from the live registry, so the file can never describe a
// tool the server does not actually serve.
func renderCatalog() ([]byte, error) {
	// The authenticator is irrelevant to the catalog and would otherwise read env vars that
	// are unset outside the Lambda.
	restore := createServerAuth
	createServerAuth = func() mcpserver.Authenticator { return nil }
	defer func() { createServerAuth = restore }()

	catalog := toolCatalog{
		Name:    serverName,
		Version: serverVersion,
		Tools:   createServer().Tools(),
	}

	rendered, err := json.MarshalIndent(catalog, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(rendered, '\n'), nil
}
