#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2024-2026 Espressif Systems (Shanghai) CO LTD
#
# SPDX-License-Identifier: Apache-2.0

import boto3
import json
import time
import uuid
import random
import datetime
import argparse
import os
import sys
from concurrent.futures import ThreadPoolExecutor
from typing import List, Dict, Any

# Add project root to Python path
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

# Now we can import our test modules
from scripts.rmng_outputs import TEST_CONFIG_PATH, RmngSettings
from py_sdk.test_device import Device, generate_key_and_cert, device_log
from py_sdk.test_user import User
from py_sdk.test_group import Group

# Hardcoded AWS root CA certificate
CA_CERT = """-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----"""

def _test_config_users():
    try:
        with open(TEST_CONFIG_PATH) as f:
            return json.load(f).get('users', [])
    except (FileNotFoundError, json.JSONDecodeError):
        return []


def _user_from_test_config(super_admin):
    """(username, password) of the first matching user in test_config.json; ("", "") if absent."""
    for user in _test_config_users():
        if bool(user.get('super_admin', False)) == super_admin and user.get('name') and user.get('password'):
            return user['name'], user['password']
    return "", ""


class TSPerformanceTester:
    def __init__(self):
        try:
            settings = RmngSettings.from_source()
        except (FileNotFoundError, SystemExit) as e:
            print(f"Error reading the deployment outputs: {e}")
            print("Please ensure you have deployed the CDK stacks and rmng-outputs.json exists.")
            sys.exit(1)

        self.region = settings.region
        self.iot_endpoint = settings.iot_endpoint
        self.api_gateway_url = settings.api_gateway_url
        self.user_api_gateway_url = settings.user_api_gateway_url
        self.identity_pool_id = settings.identity_pool_id

        common = dict(
            region=settings.region,
            identity_pool_id=settings.identity_pool_id,
            api_gateway_url=settings.api_gateway_url,
            user_api_gateway_url=settings.user_api_gateway_url,
            iot_endpoint=settings.iot_endpoint,
        )

        # Perf-test identity: the first regular user from test_config.json (generated by
        # cli/morpheus.py --setup-test-data) — the single source of test creds.
        perf_user, perf_password = _user_from_test_config(super_admin=False)
        if not perf_user or not perf_password:
            print("Error: no regular user in test_config.json; run cli/morpheus.py --setup-test-data first.")
            sys.exit(1)
        self.test_user = User(perf_user, perf_password,
                              end_user_pool_id=settings.end_user_pool_id, **common)
        self.test_user.register_user_via_lambda(email=self.test_user.username, password=self.test_user.password)
        self.test_user.get_aws_credentials()

        # Registering a node is superadmin-only, and the perf user is deliberately a regular user,
        # so keep a separate admin session purely for registration.
        admin_user, admin_password = _user_from_test_config(super_admin=True)
        if not admin_user or not admin_password:
            print("Error: no super admin in test_config.json; run cli/morpheus.py --setup-test-data first.")
            sys.exit(1)
        self.admin_user = User(admin_user, admin_password, is_super_admin=True,
                               admin_user_pool_id=settings.admin_user_pool_id,
                               admin_client_id=settings.admin_client_id, **common)
        self.admin_user.get_cognito_token()

        # Create group API
        self.group_api = Group(self.test_user)
        
        # Create a test group
        self.group_id = self.group_api.create_group("TS Performance Test Group")
        print(f"Created test group: {self.group_id}")
        
        self.devices = []  # Keep track of created devices
        
    def create_test_device(self, device_name: str = None) -> Device:
        """Create a test device with certificates."""
        if device_name is None:
            device_name = f"ts-perf-test-{uuid.uuid4()}"
            
        # Generate key and certificate
        private_key_pem, cert_pem = generate_key_and_cert(device_name, 'rsa')
        
        # Create device
        device = Device(device_name, private_key_pem, cert_pem, CA_CERT, 
                       self.iot_endpoint, self.region, debug=False)
        
        # Register through the admin API as the super admin; API Gateway supplies the caller
        # identity the handler authorizes against.
        if not self.admin_user.register_node(device, tags=["created_by:ts-perf"]):
            raise Exception(f"Failed to register device {device_name}")
            
        # Associate device with the test group
        result = self.test_user.do_user_node_assoc(device, self.group_id)
        if result is not None:
            raise Exception(f"Failed to associate device {device_name} with group: {result}")
            
        self.devices.append(device)
        return device
        
    def run_performance_test(self, num_devices: int = 1, data_points_per_device: int = 100,
                           concurrent_devices: int = 1, delay_between_points: float = 0.1):
        """Run a performance test with multiple devices publishing data points."""
        print(f"Starting performance test with:")
        print(f"- Number of devices: {num_devices}")
        print(f"- Data points per device: {data_points_per_device}")
        print(f"- Concurrent devices: {concurrent_devices}")
        print(f"- Delay between points: {delay_between_points}s")
        
        try:
            # Create test devices
            print("\nCreating test devices...")
            devices = []
            for i in range(num_devices):
                device = self.create_test_device()
                devices.append(device)
                print(f"Created device {i+1}/{num_devices}: {device.node_thing_name}")
                
            # Connect all devices
            print("\nConnecting devices...")
            for device in devices:
                if not device.connect():
                    print(f"Failed to connect device {device.node_thing_name}")
                    continue
                if not device.get_group_info():
                    print(f"Failed to get group info for device {device.node_thing_name}")
                    continue
                print(f"Connected device {device.node_thing_name}")
                
            # Function to run test for a single device
            def run_device_test(device: Device):
                device_log(f"Starting test for device {device.node_thing_name}")
                start_time = time.time()
                success_count = 0
                
                for i in range(data_points_per_device):
                    # Generate test data
                    value = random.uniform(20.0, 30.0)  # Random temperature between 20-30°C
                    timestamp = int(time.time() * 1000)  # Current time in milliseconds
                    
                    # Publish data point
                    success = device.publish_timeseries_data(
                        k="temperature",
                        data_type="float",
                        value=value,
                        timestamp=timestamp
                    )
                    
                    if success:
                        success_count += 1
                        
                    if delay_between_points > 0:
                        time.sleep(delay_between_points)
                        
                end_time = time.time()
                duration = end_time - start_time
                rate = data_points_per_device / duration if duration > 0 else 0
                
                device_log(f"Device {device.node_thing_name} completed:")
                device_log(f"- Success rate: {success_count}/{data_points_per_device}")
                device_log(f"- Duration: {duration:.2f}s")
                device_log(f"- Rate: {rate:.2f} points/s")
                
                return {
                    'device_id': device.node_thing_name,
                    'success_count': success_count,
                    'duration': duration,
                    'rate': rate
                }
                
            # Run tests using thread pool
            print(f"\nRunning performance test with {concurrent_devices} concurrent devices...")
            with ThreadPoolExecutor(max_workers=concurrent_devices) as executor:
                results = list(executor.map(run_device_test, devices))
                
            # Calculate and print summary statistics
            total_points = sum(r['success_count'] for r in results)
            total_duration = max(r['duration'] for r in results)
            overall_rate = total_points / total_duration if total_duration > 0 else 0
            
            print("\nTest Results:")
            print(f"Total data points sent: {total_points}")
            print(f"Total test duration: {total_duration:.2f}s")
            print(f"Overall throughput: {overall_rate:.2f} points/s")
            
            # Print individual device statistics
            print("\nPer-device Statistics:")
            for result in results:
                print(f"\nDevice {result['device_id']}:")
                print(f"- Success rate: {result['success_count']}/{data_points_per_device}")
                print(f"- Duration: {result['duration']:.2f}s")
                print(f"- Rate: {result['rate']:.2f} points/s")
                
        finally:
            # Clean up
            print("\nCleaning up test devices...")
            for device in devices:
                try:
                    device.disconnect()
                    device.destroy_test_node()
                    print(f"Cleaned up device {device.node_thing_name}")
                except Exception as e:
                    print(f"Error cleaning up device {device.node_thing_name}: {e}")
                    
            # Clean up test group
            try:
                self.group_api.delete_group(self.group_id)
                print(f"Cleaned up test group {self.group_id}")
            except Exception as e:
                print(f"Error cleaning up group {self.group_id}: {e}")

def main():
    parser = argparse.ArgumentParser(description='Time Series Performance Testing Tool')
    parser.add_argument('--devices', type=int, default=1,
                      help='Number of test devices to create')
    parser.add_argument('--points', type=int, default=100,
                      help='Number of data points per device')
    parser.add_argument('--concurrent', type=int, default=1,
                      help='Number of devices to run concurrently')
    parser.add_argument('--delay', type=float, default=0.1,
                      help='Delay between data points in seconds')
    
    args = parser.parse_args()
    
    tester = TSPerformanceTester()
    tester.run_performance_test(
        num_devices=args.devices,
        data_points_per_device=args.points,
        concurrent_devices=args.concurrent,
        delay_between_points=args.delay
    )

if __name__ == "__main__":
    main() 